Vendor Onboarding System/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using Newtonsoft.Json;
using System.Diagnostics;
using Vendor_Onboarding_System.Localize;
using Vendor_Onboarding_System.Models;
using VOS.Models;
using VOS.Services;

namespace Vendor_Onboarding_System.Controllers
{
    public class HomeController : Controller
    {

        #region Session
        private string ConnectionString
        {
            get
            {
                try
                {
                    return JsonConvert.DeserializeObject<string>(HttpContext.Session.GetString("ConnectionString"));
                }
                catch
                {
                    return null;
                }
            }
        }

        private dbVendorAkun_Model CurrLoginUser
        {
            get
            {
                try
                {
                    return JsonConvert.DeserializeObject<dbVendorAkun_Model>(HttpContext.Session.GetString("CurrLoginUser"));
                }
                catch
                {
                    return null;
                }
            }
        }
        #endregion

        private readonly IStringLocalizer<Resource> _stringLocalizer;
        private readonly ILogger<HomeController> _logger;
        private readonly IConfiguration _config;
        private static Random random = new Random();

        CompanyProfileService mCompanyProfileService = new CompanyProfileService();

        public HomeController(ILogger<HomeController> logger, IConfiguration config, IStringLocalizer<Resource> stringLocalizer)
        {
            _logger = logger;
            _config = config;
            _stringLocalizer = stringLocalizer;
        }

        public IActionResult Index()
        {
            HttpContext.Session.SetString("ConnectionString", JsonConvert.SerializeObject(_config.GetValue<string>("DBConnection")));
            HttpContext.Session.SetString("EmailFrom", JsonConvert.SerializeObject(_config.GetValue<string>("EmailFrom")));
            HttpContext.Session.SetString("PasswordFrom", JsonConvert.SerializeObject(_config.GetValue<string>("PasswordFrom")));
            HttpContext.Session.SetString("SMTP", JsonConvert.SerializeObject(_config.GetValue<string>("SMTP")));
            HttpContext.Session.SetString("Port", JsonConvert.SerializeObject(_config.GetValue<int>("Port")));

            ViewBag.Local = _stringLocalizer;
            if (CurrLoginUser == null)
            {
                ViewBag.Login = false;
            }
            else
            {
                ViewBag.Login = true;
                ViewBag.Category = CurrLoginUser.Category;
            }
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        #region Get Country Detail
        CountryDetailService mCountryDetail = new CountryDetailService();
        public JsonResult GetAllCountry()
        {
            try
            {
                return Json(new Response<List<dbCountry_Model>>
                {
                    Status = "Success",
                    Value = mCountryDetail.GetAllCountry(ConnectionString)
                });
            }
            catch
            {
                return Json(new Response<string>
                {
                    Status = "Failed",
                    Message = "Failed to load country list."
                });
            }
        }
        public JsonResult GetAllStateByCountryID(int CountryID)
        {
            try
            {
                return Json(new Response<List<dbProvince_Model>>
                {
                    Status = "Success",
                    Value = mCountryDetail.GetAllStateByCountryID(ConnectionString, CountryID)
                });
            }
            catch
            {
                return Json(new Response<string>
                {
                    Status = "Failed",
                    Message = "Failed to load state list."
                });
            }
        }

        public JsonResult GetAllCitiesByStateID(int StateID)
        {
            try
            {
                return Json(new Response<List<dbCity_Model>>
                {
                    Status = "Success",
                    Value = mCountryDetail.GetAllCitiesByStateID(ConnectionString, StateID)
                });
            }
            catch
            {
                return Json(new Response<string>
                {
                    Status = "Failed",
                    Message = "Failed to load city list."
                });
            }
        }
        #endregion

        public static string RandomString(int length)
        {
            const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
            return new string(Enumerable.Repeat(chars, length)
                .Select(s => s[random.Next(s.Length)]).ToArray());
        }

        public JsonResult Register(string Email, string CompanyName, string CompanyType, string Website, string PICName, string Category, string BentukUsaha, string NPWP, string TaxID, string Address, string Negara, string Provinsi, string Kota, string Kec, string ZipCode, string NoTelp)
        {

            try
            {
                mCompanyProfileService.RegisterUser(ConnectionString, new dbVendorAkun_Model()
                {
                    Email = Email,
                    Password = Encryptor.Encrypt(RandomString(15)),
                    CompanyName = CompanyName,
                    Website = Website,
                    PICName = PICName,
                    Category = Category,
                    BentukUsaha = BentukUsaha,
                    CompanyType = CompanyType,
                    NPWP = NPWP,
                    TaxID = TaxID,
                    Address = Address,
                    Negara = Negara,
                    Provinsi = Provinsi,
                    Kota = Kota,
                    Kec = Kec,
                    ZipCode = ZipCode,
                    NoTelp = NoTelp,
                    Flag = 0
                });

                return Json(new Response<string>()
                {
                    Status = "Success"
                });
            }
            catch (Exception ex)
            {
                var customMessage = ex.Message;
                if (customMessage.Contains("Cannot insert duplicate key row in object 'dbo.dbVendorAkun' with unique index 'IX_dbVendorAkun'."))
                {
                    customMessage = "Email already taken.";
                }
                return Json(new Response<string>()
                {
                    Status = "Failed",
                    Message = customMessage
                });
            }
        }

    }
}

Vendor Onboarding System/Controllers/RegistrationController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using Newtonsoft.Json;
using System.Diagnostics;
using Vendor_Onboarding_System.Localize;
using Vendor_Onboarding_System.Models;
using VOS.Models;
using VOS.Services;

namespace Vendor_Onboarding_System.Controllers
{
    public class RegistrationController : Controller
    {

        #region Session
        private string ConnectionString
        {
            get
            {
                try
                {
                    return JsonConvert.DeserializeObject<string>(HttpContext.Session.GetString("ConnectionString"));
                }
                catch
                {
                    return null;
                }
            }
        }

        private dbVendorAkun_Model CurrLoginUser
        {
            get
            {
                try
                {
                    return JsonConvert.DeserializeObject<dbVendorAkun_Model>(HttpContext.Session.GetString("CurrLoginUser"));
                }
                catch
                {
                    return null;
                }
            }
        }
        #endregion

        private readonly IStringLocalizer<Resource> _stringLocalizer;
        private readonly ILogger<RegistrationController> _logger;
        private readonly IConfiguration _config;
        private static Random random = new Random();

        CompanyProfileService mCompanyProfileService = new CompanyProfileService();

        public RegistrationController(ILogger<RegistrationController> logger, IConfiguration config, IStringLocalizer<Resource> stringLocalizer)
        {
            _logger = logger;
            _config = config;
            _stringLocalizer = stringLocalizer;
        }

        public IActionResult Index()
        {
            HttpContext.Session.SetString("ConnectionString", JsonConvert.SerializeObject(_config.GetValue<string>("DBConnection")));
            HttpContext.Session.SetString("EmailFrom", JsonConvert.SerializeObject(_config.GetValue<string>("EmailFrom")));
            HttpContext.Session.SetString("PasswordFrom", JsonConvert.SerializeObject(_config.GetValue<string>("PasswordFrom")));
            HttpContext.Session.SetString("SMTP", JsonConvert.SerializeObject(_config.GetValue<string>("SMTP")));
            HttpContext.Session.SetString("Port", JsonConvert.SerializeObject(_config.GetValue<int>("Port")));

            ViewBag.Local = _stringLocalizer;
            if (CurrLoginUser == null)
            {
                ViewBag.Login = false;
            }
            else
            {
                ViewBag.Login = true;
                ViewBag.Category = CurrLoginUser.Category;
            }
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        #region Get Country Detail
        CountryDetailService mCountryDetail = new CountryDetailService();
        public JsonResult GetAllCountry()
        {
            try
            {
                return Json(new Response<List<dbCountry_Model>>
                {
                    Status = "Success",
                    Value = mCountryDetail.GetAllCountry(ConnectionString)
                });
            }
            catch
            {
                return Json(new Response<string>
                {
                    Status = "Failed",
                    Message = "Failed to load country list."
                });
            }
        }
        public JsonResult GetAllStateByCountryID(int CountryID)
        {
            try
            {
                return Json(new Response<List<dbProvince_Model>>
                {
                    Status = "Success",
                    Value = mCountryDetail.GetAllStateByCountryID(ConnectionString, CountryID)
                });
            }
            catch
            {
                return Json(new Response<string>
                {
                    Status = "Failed",
                    Message = "Failed to load state list."
                });
            }
        }

        public JsonResult GetAllCitiesByStateID(int StateID)
        {
            try
            {
                return Json(new Response<List<dbCity_Model>>
                {
                    Status = "Success",
                    Value = mCountryDetail.GetAllCitiesByStateID(ConnectionString, StateID)
                });
            }
            catch
            {
                return Json(new Response<string>
                {
                    Status = "Failed",
                    Message = "Failed to load city list."
                });
            }
        }
        #endregion

        public static string RandomString(int length)
        {
            const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
            return new string(Enumerable.Repeat(chars, length)
                .Select(s => s[random.Next(s.Length)]).ToArray());
        }

        public JsonResult Register(string Email, string CompanyName, string CompanyType, string Website, string PICName, string Category, string BentukUsaha, string NPWP, string TaxID, string Address, string Negara, string Provinsi, string Kota, string Kec, string ZipCode, string NoTelp)
        {

            try
            {
                mCompanyProfileService.RegisterUser(ConnectionString, new dbVendorAkun_Model()
                {
                    Email = Email,
                    Password = Encryptor.Encrypt(RandomString(15)),
                    CompanyName = CompanyName,
                    Website = Website,
                    PICName = PICName,
                    Category = Category,
                    BentukUsaha = BentukUsaha,
                    CompanyType = CompanyType,
                    NPWP = NPWP,
                    TaxID = TaxID,
                    Address = Address,
                    Negara = Negara,
                    Provinsi = Provinsi,
                    Kota = Kota,
                    Kec = Kec,
                    ZipCode = ZipCode,
                    NoTelp = NoTelp,
                    Flag = 0
                });

                return Json(new Response<string>()
                {
                    Status = "Success"
                });
            }
            catch (Exception ex)
            {
                var customMessage = ex.Message;
                if (customMessage.Contains("Cannot insert duplicate key row in object 'dbo.dbVendorAkun' with unique index 'IX_dbVendorAkun'."))
                {
                    customMessage = "Email already taken.";
                }
                return Json(new Response<string>()
                {
                    Status = "Failed",
                    Message = customMessage
                });
            }
        }

    }
}

Vendor Onboarding System/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}

@Html.Partial("Modals")
<div id="main">
    @Html.Partial("Main")
</div>

<!-- Functions -->
<script>
$(function() {
    reset();
    location.href = '#hero';
});

function reset() {
    $(".select")
        .find('option')
        .remove()
        .end()
        .append('<option hidden selected value=""></option>')
        .val('');
    $('.ru1').val("");
    $('.ru2').val("");
    $('.lg').val("");
}

$('#form_Login').on('submit', function(event) {
    event.preventDefault();

    $.ajax({
        url: '/Login/Login',
        datatype: 'json',
        type: 'post',
        data: {
            "Email": $('#lu_Email').val(),
            "Password": $('#lu_Password').val()
        },
        contenttype: 'application/json; charset=utf-8',
        async: true,
        success: function(data) {
            if (data != "Success") {
                toastr.error(data);
            }
            else if (data == "Success") {
                window.location.href = "/";
            }
        },
        fail: function(xhr, textStatus, errorThrown) {
            alert('Failed.');
        }
    });
});

function adaptModal() {
    var kosong = 0;
    $('.ru1').each(function() {
        if ($(this).val() == "" || $(this).val() == null) {
            $(this).addClass("is-invalid");
            kosong = 1;
        }
    });

    var blmPilihTipe = 0;
    if ($("input[name='radioCompanyType']:checked").val() == "Local") {
        $("#local").prop("hidden", false);
        $("#foreign").prop("hidden", true);
    } else if ($("input[name='radioCompanyType']:checked").val() == "Foreign") {
        $("#local").prop("hidden", true);
        $("#foreign").prop("hidden", false);
    } else {
        blmPilihTipe = 1;
        //    toastr.warning("Please choose your company type!");
    }
    if (kosong == 0 && blmPilihTipe == 0) {
        GetAllCountry();
    } else if (kosong == 1) {
        toastr.warning("Please fill all required data.");
    } else if (blmPilihTipe == 1) {
        toastr.warning("Please choose your company type.");
    }
}

function formatNpwp(value) {
    if (typeof value === 'string') {
        return value.replace(/(\d{2})(\d{3})(\d{3})(\d{1})(\d{3})(\d{3})/, '$1.$2.$3.$4-$5.$6');
    }
}

$('#btnSaveChanges').on('click', function() {
    var kosong = 0;
    var CompanyType = "";
    $('.ru2').each(function() {
        if ($(this).val() == "" || $(this).val() == null) {
            $(this).addClass("is-invalid");
            kosong = 1;
        }
    });
    if ($("input[name='radioCompanyType']:checked").val() == "Local") {
        CompanyType = "Local";
        if ($('#ru_NPWP').val() == "") {
            $('#ru_NPWP').addClass("is-invalid");
            kosong = 1;
        }
    } else if ($("input[name='radioCompanyType']:checked").val() == "Foreign") {
        CompanyType = "Foreign";
        if ($('#ru_TaxID').val() == "") {
            $('#ru_TaxID').addClass("is-invalid");
            kosong = 1;
        }
    }

var NPWP = formatNpwp($('#ru_NPWP').val());

    if (kosong == 0 && $('#agreeTermCondition').prop("checked") == true) {
        $.ajax({
            url: '/Home/Register',
            data: {
                "Email": $('#ru_Email').val(),
                "CompanyName": $('#ru_CompanyName').val(),
                "Website": $('#ru_Website').val(),
                "PICName": $('#ru_PICName').val(),
                "Category": null,
                "BentukUsaha": $('#ru_BadanUsaha').val(),
                "CompanyType": CompanyType,
                "NPWP": NPWP,
                "TaxID": $('#ru_TaxID').val(),
                "Address": $('#ru_CompanyAddress').val(),
                "Negara": $('#ru_Country').val(),
                "Provinsi": $('#ru_Province').val(),
                "Kota": $('#ru_City').val(),
                "Kec": $('#ru_District').val(),
                "ZipCode": $('#ru_ZipCode').val(),
                "NoTelp": $('#ru_PhoneNumber').val()
            },
            dataType: 'json',
            success: function(data) {
                if (data.status == "Success") {
                    reset();
                    toastr.success('Registered successfully.');
                }
                else {
                    toastr.warning(data.message);
                }
            },
            error: function(err) { }
        });

    } else if (kosong == 0 && $('#agreeTermCondition').prop("checked") == false) {
        toastr.warning("Please agree to the term and condition.");
        alert(CompanyType);
    } else if (kosong == 1) {
        toastr.warning("Please fill all required data.");
    }
});

function GetAllCountry() {
    $.ajax({
        url: '/Home/GetAllCountry',
        data: {
        },
        dataType: 'json',
        success: function(data) {
            if (data.status == "Success") {
                $(".singleCountry")
                    .find('option')
                    .remove()
                    .end()
                    .append('<option hidden selected value=""></option>')
                    .val('');

                $.each(data.value, function(i, data) {
                    var div_data = "<option value=" + data.id + ">" + data.name + "</option>";
                    $(div_data).appendTo('.singleCountry');
                });
                $('#modalDetailReg').modal('show');
            }
            else {
                toastr.warning(data.message);
            }
        },
        error: function(err) { }
    });
}
function GetAllProvinceByCountryID(countryID) {
    $.ajax({
        url: '/Home/GetAllStateByCountryID',
        data: {
            CountryID: countryID
        },
        dataType: 'json',
        success: function(data) {
            if (data.status == "Success") {
                $(".singleProvince")
                    .find('option')
                    .remove()
                    .end()
                    .append('<option hidden selected value=""></option>')
                    .val('');

                $.each(data.value, function(i, data) {
                    var div_data = "<option value=" + data.id + ">" + data.name + "</option>";
                    $(div_data).appendTo('.singleProvince');
                });
            }
            else {
                toastr.warning(data.message);
            }
        },
        error: function(err) { }
    });
}
function GetAllCityByProvinceID(provID) {
    removeIsInvalidOne("ru_Province");
    $.ajax({
        url: '/Home/GetAllCitiesByStateID',
        data: {
            StateID: provID
        },
        dataType: 'json',
        success: function(data) {
            if (data.status == "Success") {
                $(".singleCity")
                    .find('option')
                    .remove()
                    .end()
                    .append('<option hidden selected value=""></option>')
                    .val('');

                $.each(data.value, function(i, data) {
                    var div_data = "<option value=" + data.id + ">" + data.name + "</option>";
                    $(div_data).appendTo('.singleCity');
                });
            }
            else {
                toastr.warning(data.message);
            }
        },
        error: function(err) { }
    });
}

</script>

Vendor Onboarding System/Views/Home/Main.cshtml
<!-- ======= Hero Section ======= -->
<section id="hero">
    <div class="container">
        <div class="row justify-content-between">
            <div class="col-lg-6 pt-5 pt-lg-0 order-2 order-lg-1 d-flex align-items-center">
                <div class="text-left">
                    <h1>@ViewBag.Local["hello_welcome"].Value</h1>
                    <h1 class="mt-2"><span>@ViewBag.Local["intikom"].Value</span></h1>
                    <div data-aos="zoom-out">
                        <br />
                        <div class="text-lg-start">
                            <a asp-controller="Registration" asp-action="Index" class="btn-get-started">@ViewBag.Local["get_started"].Value</a>
                        </div>
                    </div>
                </div>
            </div> 
            @if (ViewBag.Login == null || ViewBag.Login == false)  {
                <div class="form-hero col-lg-5 order-1 order-lg-2 text-white" data-aos="zoom-out" data-aos-delay="300">
                    <form id="form_Login">
                        <div class="p-5">
                            <div class="section-title" data-aos="fade-up">
                                <h3>@ViewBag.Local["are_you_new"].Value</h3>
                                <p>@ViewBag.Local["login_here"].Value</p>
                            </div>

                            <div class="mb-4 pb-2">
                                <div class="form-outline form-white">
                                    <div class="form-floating">
                                        <input type="text" class="form-control lg" id="lu_Email" placeholder=" ">
                                        <label for="floatingInput" style="color:#5c5c5c;">Email</label>
                                    </div>
                                </div>
                            </div>

                            <div class="mb-4 pb-2">
                                <div class="form-outline form-white">
                                    <div class="form-floating">
                                        <input type="password" class="form-control lg" id="lu_Password" placeholder=" ">
                                        <label for="floatingInput" style="color:#5c5c5c;">@ViewBag.Local["pass"].Value</label>
                                    </div>
                                </div>
                            </div>

                            <div class="row justify-content-between">
                                <div class="col-7">
                                    <div class="row"><a href="#">I forgot my password</a></div>
                                    <div class="row"><a asp-controller="Registration" asp-action="Index">Register a new membership</a></div>
                                </div><br/>
                                <div class="col-4" style="align:right;">
                                    <button type="submit" class="btn btn-light btn-lg">
                                        <h5 style="padding-top:4px;">@ViewBag.Local["sign_in"].Value</h5>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            }else{
                <div class="form-hero col-lg-5 order-1 order-lg-2 text-white" data-aos="zoom-out" data-aos-delay="300">
                    <div class="p-5">
                        <div class="section-title" data-aos="fade-up">
                            <div class="row justify-content-between">
                                <div class="col col-lg-9">
                                    <h3>@ViewBag.Local["information_news"].Value</h3>
                                </div>
                                @if (ViewBag.Category == "Admin"){
                                    <div class="col col-lg-2">
                                        <button class="btn btn-primary waves-effect waves-light" onclick="$('#modalAddInformation').modal('show');">
                                            <i class="fas fa-plus fa-sm"></i>
                                        </button>
                                    </div>
                                }
                            </div>
                        </div>
                        <div id="news" class="carousel slide carousel-multi-item" data-ride="carousel">
                            <ol class="carousel-indicators">
                                <li data-target="#multi-item-example" data-slide-to="0" class="active"></li>
                                <li data-target="#multi-item-example" data-slide-to="1" class=""></li>
                            </ol>
                            
                            <div class="carousel-inner" role="listbox">
                                <div class="carousel-item active">
                                    <div class="card mb-2">
                                        <img class="card-img-top" src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/4-col/img%20(34).webp" alt="Card image cap">
                                        <div class="card-body">
                                            <h4 class="card-title">Card title</h4>
                                            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the
                                            card's
                                            content.</p>
                                            <a class="btn btn-primary waves-effect waves-light">Read more</a>
                                        </div>
                                    </div>
                                </div>
                                <div class="carousel-item">
                                    <div class="card mb-2">
                                        <img class="card-img-top" src="https://mdbootstrap.com/img/Photos/Horizontal/City/4-col/img%20(60).webp" alt="Card image cap">
                                        <div class="card-body">
                                            <h4 class="card-title">Card title</h4>
                                            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the
                                                card's
                                                content.</p>
                                            <a class="btn btn-primary waves-effect waves-light">Read more</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>

    <svg class="hero-waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 24 150 28 " preserveAspectRatio="none">
        <defs>
            <path id="wave-path" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z"></path>
        </defs>
        <g class="wave1">
            <use xlink:href="#wave-path" x="50" y="3" fill="rgba(255,255,255, .1)"></use>
        </g>
        <g class="wave2">
            <use xlink:href="#wave-path" x="50" y="0" fill="rgba(255,255,255, .2)"></use>
        </g>
        <g class="wave3">
            <use xlink:href="#wave-path" x="50" y="9" fill="#010351"></use>
        </g>
    </svg>

</section><!-- End Hero -->